### ISSUE TITLE
Solicitud de mentoría: Verónica Girón

### ISSUE THREAD

**Issue by veronicagironvl** [OpenScienceLabs/request-forms#11]
# ¡Requerimiento de mentorías!

Si quieres solicitar mentoría, llene el siguiente formulario:

```{note}
(*) Obligatorio.
```

- **E-mail`*`**: veronicagironvl@gmail.com
- **Nombre completo`*`**: Verónica Virginia Girón López
- **Áreas de interés para la mentoría`*`**: cybersecurity
- **URL del perfil en Linkedin**: https://www.linkedin.com/in/ver%C3%B3nica-gir%C3%B3n-1379121b4/
- **URL del perfil en Twitter**: 
- **URL del perfil en GitHub**: 

He leído el [Código de Conducta](https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo`*`: 
- [x] Sí

He leído la [Guía de Mentorías](https://opensciencelabs.github.io/mentoring/guide-en.html)`*`: 
- [x] Sí

**Comment by xmnlab** [comment]
@veronicagironvl , muchas gracias por tu solicitud. Nos podrías comentar con más detalles qué puntos de cyberseguridad te gustaría apoyo en tu mentoría? en que lo estarías aplicando? etc

@Aledonisgt podrías revisar este pedido de mentoría?

**Comment by Aledonisgt** [comment]
@xmnlab si con gusto, @veronicagironvl dime como puedo apoyarte, que tema de cibreseguridad necesitas abordar, sobre que específicamente (Análisis de vulnerabilidades, buenas prácticas, desarrollo seguro)

**Comment by veronicagironvl** [comment]
Hola, muchas gracias a ustedes por crear este espacio. Hola @Aledonisgt, un gusto conocerte. Me presento: me llamo Verónica Girón, soy de Venezuela, tengo 19 años y estoy en mi primer año de ingeniería en computación, pero quiero dedicarme a la cybersecurity, por eso estoy buscando formas de capacitarme fuera de la universidad. Estoy haciendo un curso sobre los fundamentos en edx y también estudio un poco con lo que encuentro en youtube. Por lo tanto, realmente mis dudas están orientadas a como iniciar en la cybersecurity: que lenguajes aprender, cuales skills desarrollar primero, consejos, etc y no a temas específicos porque aun no estoy tan avanzada jajajajaja. Muchas gracias por ofrecerte ayudarme!

**Comment by veronicagironvl** [comment]
Disculpen, cerré el comentario por error!

**Comment by xmnlab** [comment]
@Aledonisgt si estás de acuerdo, podemos finalizar esta issue y seguir con el tema en discord.

La manera como se maneja las mentorías es bastante abierta, uds pueden definir como será el formato.
En el pasado, hemos hecho de la siguiente manera:

1. definimos un día y una hora fija semanalmente, y usamos google calendar para gestionarlo. Si hay cambio de horarios, cambiamos en el google calendar así la mentoreada también recibe la notificación del cambio del evento.
2. uds pueden usar google meet (que ya sale configurado en google calendar), discord, o cualquier otro aplicativo. Si necesitan de cualquier cosa de discord, por favor, házmelo saber.
3. cuando empiece la mentoría, escribe un mensaje aquí esta issue y yo voy a cambiar su status de `mentoring-request` a `mentoring-started`. 
4. de la misma manera, cuando decidan terminar las mentorías, escriban a esta issue, y lo voy a cambiar de `mentoring-started` a `mentoring-finished`. quizá estos nombres cambien en un futuro, pero será algo así :)

por favor, me avisen si tienen cualquier consulta.

**Comment by Aledonisgt** [comment]
@veronicagironvl con gusto, dejame coordinar un par de sesiones y te retroalimento al respecto.

**Comment by Aledonisgt** [comment]
@xmnlab si, yo prefiero meet, pero podemos tener alguna call o míni meet para que me puedas explicar please.

**Comment by xmnlab** [comment]
@Aledonisgt , claro que sí! coordinamos via discord :)

**Comment by Aledonisgt** [comment]
@veronicagironvl  te queda bien una sesión este viernes a las 6:00 pm GTM-6?

**Comment by veronicagironvl** [comment]
Hola, si perfecto.
Podemos coordinarlo por email? Es que no uso github entonces no me notifica si tengo mensajes nuevos. Mi correo es veronicagironvl@gmail.com 

Discúlpeme por no haber respondido antes! Nuevamente muchas gracias!

**Comment by xmnlab** [comment]
@veronicagironvl disculpa el atraso de hacer un seguimiento. has podido coordinar algo con @Aledonisgt ?
me avisas si aún necesitas mentoría. saludos!

**Comment by xmnlab** [comment]
@veronicagironvl como no hemos recibido más respuestas tuyas, estamos finalizando esta issue.
esté a gusto de re-abrirla si aún estés interesada.
muchas gracias
