### ISSUE TITLE
Jemima López

### ISSUE THREAD

**Issue by jemima-lopez** [OpenScienceLabs/request-forms#12]
# ¡Convocatoria para Colaboración!

Si quieres colaborar a nuestra comunidad llene el formulario a seguir:

```{note}
(*) Obligatorio.
```

- **jlopezj11@miumg.edu.gt`*`**:
- **Jemima Antonia Noemí López Juárez`*`**:
- **creación de blogs`*`**:
  - [ ] DevOps
  - [x] Creación de Artículos (blog)
  - [ ] Producción de Videos (youtube)
  - [ ] Community Management
  - [ ] Social Media
  - [ ] Diversidad, Equidad e Inclusión
  - [ ] Organización de Eventos
  - [ ] Documentación
  - [ ] Mentoría
  - [ ] Gestión de Proyectos
- **¿Por qué quiero colaborar a la comunidad OSL?`*`**:
- **Horas semanales disponibles para dedicarme a la comunidad OSL`*`**:
  - [x] 2 horas/semana
  - [ ] 4 horas/semana
  - [ ] 6+ horas/semana
- **URL del perfil en Linkedin**: 
- **URL del perfil en Twitter**: 
- **URL del perfil en GitHub**:
- **Bio (una descripción sobre ti, similar a la usada en Linkdin o en tu CV)`*`**: 
- **URL de foto de perfil`*`**:

**He leído el Código de Conducta de OSL (https://opensciencelabs.github.io/mentoring-guideline/coc-es.html) y estoy de acuerdo`*`**:
- [* ] Sí

**NOTAS:**

- nuestra comunidad está en discord:  http://discord.opensciencelabs.org
- agrega nuestro calendario público de nuestras reuniones semanales a tu google calendar: http://calendar.opensciencelabs.org

**Comment by eunrod16** [comment]
¡Hola Jemima! ¡Bienvenida!.  Muchas gracias por tu interés en la comunidad, esperamos que entre todos podamos aprender muchas cosas interesantes. 

Me podrías apoyar con estas breves preguntas. 

1. ¿Por qué quiero colaborar a la comunidad OSL? 
2. Bio (una descripción sobre ti, similar a la usada en Linkdin o en tu CV) 

Además, te comento que tenemos una reunión los martes a las 7:00 pm CST de colaboradores (http://calendar.opensciencelabs.org)http://calendar.opensciencelabs.org/) 

De nuevo muchas gracias y esperamos verte en la reunión de colaboradores. Que estés muy bien.

**Comment by xmnlab** [comment]
hola @jemima-lopez ! alguna novedad de los puntos que comentó @eunrod16 ?
hoy tenemos reunión, el horario y el enlace de google meet está en en link que @eunrod16 escribió en su comentario.
esperamos darte las bienvenidas en una de nuestras reuniones! hasta pronto!

**Comment by xmnlab** [comment]
@jemima-lopez , nos gustaría saber si aún estás interesada en colaborar a Open Science Labs! sería un gusto tenerte abordo! me avisas si tienes cualquier duda. saludos!

**Comment by xmnlab** [comment]
como no hemos recibido respuestas, voy a cerrar esta issue.
@jemima-lopez esté a gusto de re-abrir esta issue caso aún estés interesada en este tema.
gracias
