### ISSUE TITLE
NEW CONTRIBUTOR: Luis Alexander Barrios Anyosa

### ISSUE THREAD

**Issue by chopper210397** [OpenScienceLabs/request-forms#13]
# ¡Convocatoria para Colaboración!

Si quieres colaborar a nuestra comunidad llene el formulario a seguir:

```{note}
(*) Obligatorio.
```

- **E-mail`*`**: luisbarrios2197@gmail.com
- **Nombre completo`*`**: Luis Alexander Barrios Anyosa
- **Área de interés`*`**: 
  - [ ] DevOps
  - [X] Creación de Artículos (blog)
  - [ ] Producción de Videos (youtube)
  - [ ] Community Management
  - [ ] Social Media
  - [ ] Diversidad, Equidad e Inclusión
  - [ ] Organización de Eventos
  - [X] Documentación
  - [ ] Mentoría
  - [ ] Gestión de Proyectos
- **¿Por qué quiero colaborar a la comunidad OSL?`*`**:
- **Horas semanales disponibles para dedicarme a la comunidad OSL`*`**:
  - [X] 2 horas/semana
  - [ ] 4 horas/semana
  - [ ] 6+ horas/semana
- **URL del perfil en Linkedin**: https://www.linkedin.com/in/luisalexanderbarrios
- **URL del perfil en Twitter**: 
- **URL del perfil en GitHub**:https://github.com/chopper210397
- **Bio (una descripción sobre ti, similar a la usada en Linkdin o en tu CV)`*`**: 
I´m an economist interested in econometrics, data science, and research applicated with R, Latex and Stata.

About me
🔭 I’m currently working on Laboratorios Lansier as Commercial Analyst Jr.
🌱 I’m currently learning more and more about R and Econometrics.
👯 I’m looking to collaborate on Data science or Research projects.
📫 How to reach me: [luisbarrios2197@gmail.com](mailto:luisbarrios2197@gmail.com)
- **URL de foto de perfil`*`**: https://avatars.githubusercontent.com/u/51522808?s=400&u=7b1a6c748296966650690a8fb8f7e5653c74b7b2&v=4

**He leído el Código de Conducta de OSL (https://opensciencelabs.github.io/mentoring-guideline/coc-es.html) y estoy de acuerdo`*`**:
- [X] Sí

**NOTAS:**

- nuestra comunidad está en discord:  http://discord.opensciencelabs.org
- agrega nuestro calendario público de nuestras reuniones semanales a tu google calendar: http://calendar.opensciencelabs.org

**Comment by EverVino** [comment]
Hola @chopper210397 bienvenido, gracias por el interés. Estamos teniendo reuniones de colaboradores los días martes de cada semana. te invitamos cordialmente a la siguiente reunión.
Aquí el calendario en google calendar ([http://calendar.opensciencelabs.org/](http://calendar.opensciencelabs.org)
Cualquier duda o consulta la vamos a responder en este issue. Esperamos verte en la siguiente reunión.

Hello @chopper210397! I hope you doing well. Collaborators meetings are on Tuesday every week. We'll be glad if you join us links here on google calendar([http://calendar.opensciencelabs.org/](http://calendar.opensciencelabs.org). If there any questions just drop it here(in this issue). We will be responding asap.

**Comment by xmnlab** [comment]
hola @chopper210397 ! un gusto saludarte!
hoy tenemos una reunión de nuestra comunidad, los detalles (horario y link de google meet) está aquí http://calendar.opensciencelabs.org/ (también mencionado por @EverVino )
esperamos darte las bienvenidas en una de nuestras reuniones! hasta pronto!

**Comment by xmnlab** [comment]
@chopper210397 , nos gustaría saber si aún estás interesado en colaborar a Open Science Labs. nos avisas si tienes cualquier duda. saludos!

**Comment by xmnlab** [comment]
como no hemos recibido respuesta, voy a cerrar esta issue.
@chopper210397 esté a gusto de re-abrir esta issue caso aún tengas interés en este tema.
gracias
