### ISSUE TITLE
Solicitud de mentoría: Melany Libia Estevez Camata

### ISSUE THREAD

**Issue by libialany** [OpenScienceLabs/request-forms#18]
### E-mail

elibialany@gmail.com

### Nombre Completo

Melany Libia Estevez Camata

### URL perfil Linkedin

https://www.linkedin.com/in/melany-libia-estevez-camata-79894520b

### URL perfil Twitter

https://twitter.com/ZtvmtE

### URL perfil GitHub

https://github.com/libialany

### Código de Conducta

- [X] He leído el [Código de Conducta](https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo

### Guía de Mentorías

- [X] He leído la [Guía de Mentorías](https://opensciencelabs.github.io/mentoring/guide-en.html)

**Comment by xmnlab** [comment]
Hola @libialany ! 
Te damos la bienvenida a OSL!

Qué necesitas trabajar en tu mentoría? Estás buscando resolver algún tema específico? Quieres desarrollar alguna habilidad? Coméntanos un poco más de tus necesidades y expectativas :)

**Comment by libialany** [comment]
Muchas gracias ,me gustaria aprender algo de testing y QA , superficial en Python, me encanta el Open Source y siempre voy viendo la forma de contribuir a proyectos algunos no resultaron ,tal vez por  el tema de testear antes de generar un cambio , un ejemplo es este https://github.com/hugovk/tinytext/pull/148.

**Comment by xmnlab** [comment]
Genial! creo que tenemos mentores/as para ayudarte.
me podrías decir dos mentores/as de esta lista que te gustaría solicitar la mentoría?
vamos a contactarles y ya coordinamos los próximos pasos.
de todos modos, las mentorías las organizamos en nuestro discord: https://opensciencelabs.org/discord
me pasas tu nombre de usuario allá y me conecto contigo con más detalles.

**Comment by libialany** [comment]
- Luis Gago Casas
- Ivan Ogasawara
@Baybiscuit

**Comment by luisgagocasas** [comment]
Hola! @libialany 
Yo estaría siendo el mentor asignado mucho gusto.
Podrías darnos los horarios en los cuales estarías libre.
(Ejemplo martes después de las 20:00 UTC-5 hora Perú)
Sería ideal que te nos unieras a nuestro servidor de [discord](https://discord.gg/vUMsccUS), ahí mantendríamos un registro de las conversaciones y reuniones. (Cuando lo hagas no olvides mencionarme tu nombre de usuario)
Quedo atento.

**Comment by libialany** [comment]
Hola! gracias,me gustaría recibir en mentoría , los horarios pueden ser
cualquier día,yo preferiría los miércoles, después de después de las 20:00
UTC-4, en discord estoy como @baybiscuit.

**Comment by xmnlab** [comment]
muchas gracias @luisgagocasas y @libialany !
como ya está todo en marcha, voy a cerrar esta issue!
hablamos por discord :)
