### ISSUE TITLE
Solicitud de mentoría: <INFORME SARMIENTO ANDRADE DAMARIS DAYANA>

### ISSUE THREAD

**Issue by DamarisMartina** [OpenScienceLabs/request-forms#19]
### E-mail

martinasoleo1998@gmail.com

### Nombre Completo

Damaris Dayana Sarmiento Andrade

### URL perfil Linkedin

None

### URL perfil Twitter

None

### URL perfil GitHub

https://github.com/DamarisMartina

### Código de Conducta

- [X] He leído el [Código de Conducta](https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo

### Guía de Mentorías

- [X] He leído la [Guía de Mentorías](https://opensciencelabs.github.io/mentoring/guide-en.html)

**Comment by EverVino** [comment]
Hey!  @DamarisMartina bienvenida a OSL.
Podrías indicarnos con cuál mentor estarías más cómoda, el área o tema o habilidad quisieras que esté dentro de la mentoría.
Y ¿Cuando podrías tener tiempo para un primera reunión para coordinar la mentoría? (No te olvides aclarar la zona horaria Ej. Martes después de  16:00 - UTC-4 hora Bolivia)

**Comment by EverVino** [comment]
@DamarisMartina si acaso tienes dificultades para responder, puedes iniciar sesión en github y responder la pregunta [aquí](https://github.com/OpenScienceLabs/request-forms/issues/19) o en su defecto responder al correo electrónico opensciencelabs@gmail.com Estaremos atentos a tu respuesta

**Comment by DamarisMartina** [comment]
Buen día, disculpen la demora. Les agradezco mucho hayan aceptado mi
solicitud. El mentor con el cuál me gustaría recibir mentoría con Ivan
Ogasawara para Python Científico, Python Web y C++. Podría éste martes
después de las 20:00 - UTC-4 hora Bolivia o martes entre 08:00 y 11:00  -
UTC-4 hora Bolivia.

Nuevamente les agradezco la consideración y me disculpo por la demora de mi
respuesta.

**Comment by xmnlab** [comment]
hola @DamarisMartina, sería un gusto ser tu mentor!

martes a las 20h me funciona.

las mentorías las organizamos en nuestro discord: https://opensciencelabs.org/discord
cuando puedas ingresar allá, me pasas el nombre de tu usuario y ya voy organizando los próximos pasos, te envío la invitación de la mentoría, etc

muchas gracias

**Comment by DamarisMartina** [comment]
Buenas tardes y gracias! mi nombre de usuario es DamarisMartina#9770 y ya me uní al servidor de Discord. Quedo atenta para la invitación.

**Comment by xmnlab** [comment]
@DamarisMartina el único usuario con un nombre parecido allá es `DaMartine98#5568`.
poderías verificarlo nuevamente? me puedes enviar un mensaje allá en community/general a `xmnlab`. 

muchas gracias

**Comment by DamarisMartina** [comment]
@xmnlab pude enviarte un mensaje. Acabo de verificar y no me había unido al servidor. Disculpa

**Comment by xmnlab** [comment]
hola @DamarisMartina ya te he agregado al nuestro canal de la mentoría y te envié la invitación para la mentoría en google calendario.

voy a cerrar esta issue y seguimos hablando por discord.

hasta pronto!
