### ISSUE TITLE
Improve the mentoring form

### ISSUE THREAD

**Issue by EverVino** [OpenScienceLabs/request-forms#20]
We need in the request mentoring, a field where the applicant can add what he expects from the mentorship. and which mentor you would be comfortable with, it is also possible that the mentoring applicant has chosen the mentor by clicking next to his photo on the OpenScienceLabs website, but that does not appear on the form. It would also be good to include in the form the availability of schedule, to specify a first meeting.

**Comment by xmnlab** [comment]
>  it is also possible that the mentoring applicant has chosen the mentor by clicking next to his photo on the OpenScienceLabs website, but that does not appear on the form. It would also be good to include in the form the availability of schedule, to specify a first meeting.

@EverVino not sure yet if that is possible, that would be great. @luabida could you help us to investigate that pls?

> We need in the request mentoring, a field where the applicant can add what he expects from the mentorship

yep, I can do that, thanks!

**Comment by luabida** [comment]
@xmnlab Ok, I'll take a look into it
