### ISSUE TITLE
Solicitud de mentoría: Luis Paulo Lemke

### ISSUE THREAD

**Issue by Luislemke** [OpenScienceLabs/request-forms#23]
### E-mail

luisdoslemke@gmail.com

### Nombre Completo

Luis Paulo Lemke

### Las(os) Mentoras(os)

Ivan Ogasawara

### Expectativas

Eu trabalhei 15 anos em uma empresa de motores, estudei o que pude lá, mas depois de tanto tempo não estava mais animado pra trabalhar nesse ramo, ai cansado eu entrei pra área de T.I. quero tentar crescer. Eu descobri que sou muito bom em lógica, mas eu estou precisando melhorar minhas bases, e ter competência de poder agregar e desenvolver códigos com mais independência e segurança. Além também de estar buscando uma oportunidade de trabalho. Acredito que com um bom mentor sua colaboração  irei alcançar todos meus objetivos.

### Horario de la Primera Reunión

hoje 30/01/2023 horário 15:00h, Brasília/Brasil 

### URL perfil Linkedin

https://www.linkedin.com/in/luis-paulo-lemke-85778524a/

### URL perfil GitHub

https://github.com/Luislemke

### Código de Conducta

- [X] He leído el [Código de Conducta](https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo

### Guía de Mentorías

- [X] He leído la [Guía de Mentorías](https://opensciencelabs.github.io/mentoring/guide-en.html)

**Comment by xmnlab** [comment]
olá @Luislemke ! bem vindo a Open Science Labs!!

vc tem alguma linguagem q vc gostaria de aprender?
Python, JavaScript, C++, Java, etc?

**Comment by Luislemke** [comment]
Boa tarde, na verdade eu já fiz cursos em Python, e estou estudando node.js mas eu estou aqui pra aprender tudo que for necessário pra consegui um trabalho.. e evoluir hehehe Enviado do Email para Windows De: Ivan OgasawaraEnviado:segunda-feira, 30 de janeiro de 2023 14:35Para: OpenScienceLabs/request-formsCc:Luislemke; MentionAssunto: Re: [OpenScienceLabs/request-forms] Solicitud de mentoría: Luis Paulo Lemke (Issue #23) olá @Luislemke ! bem vindo a Open Science Labs!!vc tem alguma linguagem q vc gostaria de aprender?Python, JavaScript, C++, Java, etc?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by xmnlab** [comment]
super! gostaría de saber se vc estaría interessado em ter mentoría com Mateus Venâncio: https://opensciencelabs.org/mentoring/mentors/

estamos tratando de equalizar as mentorías, como eu já estou dando mentoría e vc não tem uma necessidade muito específica, então talvez Mateus poderia te ajudar a se desenvolver usando nodejs.

poderia ser?

**Comment by Luislemke** [comment]
Olha tranquilo, qualquer ajuda é bem vinda hehehhe  Enviado do Email para Windows De: Ivan OgasawaraEnviado:segunda-feira, 30 de janeiro de 2023 14:57Para: OpenScienceLabs/request-formsCc:Luislemke; MentionAssunto: Re: [OpenScienceLabs/request-forms] Solicitud de mentoría: Luis Paulo Lemke (Issue #23) super! gostaría de saber se vc estaría interessado em ter mentoría com Mateus Venâncio: https://opensciencelabs.org/mentoring/mentors/estamos tratando de equalizar as mentorías, como eu já estou dando mentoría e vc não tem uma necessidade muito específica, então talvez Mateus poderia te ajudar a se desenvolver usando nodejs.poderia ser?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Luislemke** [comment]
> super! gostaría de saber se vc estaria interessado em ter mentoria com Mateus Venâncio: https://opensciencelabs.org/mentoring/mentors/
> 
> estamos tratando de equalizar as mentorías, como eu já estou mentoria e vc não tem uma necessidade muito específica, então talvez dando Mateus poderia te ajudar a se desenvolver usando nodejs.
> 
> poderia ser?
,ola, pode , qualquer ajuda é bem vinda, e eu tbm gostaria de me aprofundar em Python

**Comment by xmnlab** [comment]
Cool. Então talvez vc poderia começar com o Mateus e depois qnd terminar a mentoría com ele vc pode abrir outra solicitação específica para trabalhar com Python. Até lá creio que vamos ter mais mentores/mentoras para ajudar com Python que no grupo de lingua portuguesa :)

@mateushvenancio vc estaría disponível para dar mentoría?

**Comment by mateushvenancio** [comment]
Claro, estou sim!

**Comment by xmnlab** [comment]
Super! Vou criar um canal no discord pra mentoría de vcs!!
