### ISSUE TITLE
Solicitud de mentoría: Anavelyz Perez

### ISSUE THREAD

**Issue by Anavelyz** [OpenScienceLabs/request-forms#24]
### E-mail

anavelyz@gmail.com

### Nombre Completo

Anavelyz Perez

### Las(os) Mentoras(os)

Mateus Venâncio

### Expectativas

Tener conocimiento y experiencia en el uso de Flutter bajo buenas prácticas.

### Horario de la Primera Reunión

Martes 2PM UTC -4

### URL perfil Linkedin

https://www.linkedin.com/in/anavelyz-perez-5b1161117

### URL perfil Twitter

https://twitter.com/AnavelyzJPR

### URL perfil GitHub
[
github.com/Anavelyz/](https://github.com/Anavelyz/)

### Código de Conducta

- [X] He leído el [Código de Conducta](https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo

### Guía de Mentorías

- [X] He leído la [Guía de Mentorías](https://opensciencelabs.github.io/mentoring/guide-en.html)

**Comment by xmnlab** [comment]
@mateushvenancio vc poderia dar essa mentoría?

**Comment by mateushvenancio** [comment]
Claro, posso sim!

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by xmnlab** [comment]
ok .. voy a crear un grupo en discord para uds puedan coordinar !

**Comment by xmnlab** [comment]
done
