### ISSUE TITLE
Internship Application: Rochana S

### ISSUE THREAD

**Issue by roch07** [OpenScienceLabs/request-forms#28]
### E-mail

srochana6@gmail.com

### Full Name

Rochana S

### Bio

I am a very enthusiastic person who is ready to explore new things every day. I am looking forward to a new experience, to learn and be helpful in everyway.I am here to explore new paths, embrace curiosity, and push my limits to expand my horizons and discover my full potential.

### Send your CV

- [X] I have sent my CV to opensciencelabs@gmail.com

### What projects are you interested in?

- [ ] scicookie, is a template developed by Open Science Labs that creates projects from project templates and is based on Cookieninja A Cookiecutter Fork command-line utility. [Repository](https://github.com/osl-incubator/scicookie)
- [ ] makim, is based on make and focus on improve the way to define targets and dependencies. Instead of using the Makefile format, it uses yaml format [Repository](https://github.com/osl-incubator/makim)
- [ ] containers-sugar. The idea of this project is to organize your stack of containers, gathering some useful scripts and keeping this information centralized in a configuration file. So the command line would be very simple. [Repository](https://github.com/osl-incubator/containers-sugar)
- [X] github-actions-chatgpt-pr-reviewer. This GitHub actions uses OpenAI ChatGPT in order to review the changes presented in a PR and will recommend improvements. [Repository](https://github.com/osl-incubator/github-actions-chatgpt-pr-reviewer)
- [ ] semantic-release-pr-title-check. Checks for Angular commit message format in the Pull Request Title. [Repository](https://github.com/osl-incubator/semantic-release-pr-title-check)
- [X] satellite-weather-downloader, is a system for downloading, transforming and analysing Copernicus weather data using Xarray. It consists in two major apps, satellite_downloader and satellite_weather. [Repository](https://github.com/osl-incubator/satellite-weather-downloader)
- [ ] CrawlClima. This package contains the PEGATWEETS and PEGATEMPERATURA modules for automatically capturing tweets and weather data. [Repository](https://github.com/osl-incubator/CrawlClima)
- [ ] dowloader-app. A shapefiles downloader. [Repository](https://github.com/osl-incubator/downloader-app)
- [ ] conda-forge-warning. Conda-Forge Warning aims to present conda-forge package without maintenance. [Repository](https://github.com/osl-incubator/conda-forge-warning)
- [X] pyreaddbc, is a Python library for working with DBase database file. Legacy systems from the Brazilian Ministry of Health still uses DBF and DBC formats to Publicize data. [Repository](https://github.com/osl-incubator/pyreaddbc)
- [ ] ghreport. A GitHub Report tool. [Repository](https://github.com/osl-incubator/ghreport)
- [ ] gh-check-pr-is-updated. This GitHub actions aims to check if the current PR's branch is updated on top of the upstream branch. [Repository](https://github.com/osl-incubator/gh-check-pr-is-updated)
- [X] github-actions-self-hosted-runner. Dockerfile for the creation of a GitHub Actions runner image to be deployed dynamically. [Repository](https://github.com/osl-incubator/github-actions-self-hosted-runner)
- [X] fqlearn. A graphic solver tool to teach mass transfer and thermodynamics.[Repository](https://github.com/osl-pocs/mass-transfer-py)
- [X] pydatastructs. A project that aims to be a Python package for various data structures and algorithms (including their parallel implementations).[Repository](https://github.com/codezonediitj/pydatastructs/)

### Code of Conduct

- [X] I have read the [Code of Conduct](https://opensciencelabs.github.io/coc/coc-es.html) and I agree.

**Comment by xmnlab** [comment]
Hi @roch07 !

Thanks for applying!

We are reviewing your application and we will answer in 1 or 2 weeks after the application deadline. 
In the meantime we maybe will request for more details here.

Thank you!

**Comment by roch07** [comment]
Hello! Thank you for letting me know about the review timeline for my
application. I look forward to hearing from you in 1 or 2 weeks. If you
need any additional information in the meantime, please feel free to reach
out. Have a great day!
Rochana S

**Comment by EverVino** [comment]
Hi! @roch07 We have reviewed your application, thank you for applying. We have a few questions before we continue.
We understand that everyone has a unique schedule, and we want to make sure the internship can work for you. Could share your availability with us? Tell us how many hours per week you can dedicate to the internship, and if you have any preferred start and end dates, please let us know. This information will help us tailor the internship experience suits your needs.

**Comment by roch07** [comment]
I appreciate your flexibility regarding my schedule. Due to my college
commitments, I can dedicate approximately 3 hours per day after 20:00 IST
to the internship. I believe this level of commitment will allow me to
contribute effectively while balancing my academic responsibilities.
Thank you for your consideration
Looking forward to hearing from you

**Comment by EverVino** [comment]
Dear @roch07 ,

Thank you for your application to the Open Science Labs Internship Program.

We're excited to share that we've completed our selection process. You will receive an email from us tomorrow with the results.

Your patience and interest are greatly appreciated. If you have questions, contact us at opensciencelabs@gmail.com

Thank you for being part of our process.
