### ISSUE TITLE
Internship Application: Romeo Montalvo

### ISSUE THREAD

**Issue by AYOHTEE** [OpenScienceLabs/request-forms#29]
### E-mail

rmontalvo2@mac.com

### Full Name

Romeo Montalvo

### URL perfil Linkedin

https://www.linkedin.com/in/romeomontalvo

### Bio

Hi there,

A little about me, I am curious and problem-solving, work well in groups or individually. Have been involved in various industries, at different capacities including agriculture, technology, agricultural technology (AgTech), entomology, aquaculture, leadership, training, product development, research and development, production/manufacturing, 

### Send your CV

- [ ] I have sent my CV to opensciencelabs@gmail.com

### What projects are you interested in?

- [X] scicookie, is a template developed by Open Science Labs that creates projects from project templates and is based on Cookieninja A Cookiecutter Fork command-line utility. [Repository](https://github.com/osl-incubator/scicookie)
- [X] makim, is based on make and focus on improve the way to define targets and dependencies. Instead of using the Makefile format, it uses yaml format [Repository](https://github.com/osl-incubator/makim)
- [X] containers-sugar. The idea of this project is to organize your stack of containers, gathering some useful scripts and keeping this information centralized in a configuration file. So the command line would be very simple. [Repository](https://github.com/osl-incubator/containers-sugar)
- [X] github-actions-chatgpt-pr-reviewer. This GitHub actions uses OpenAI ChatGPT in order to review the changes presented in a PR and will recommend improvements. [Repository](https://github.com/osl-incubator/github-actions-chatgpt-pr-reviewer)
- [X] semantic-release-pr-title-check. Checks for Angular commit message format in the Pull Request Title. [Repository](https://github.com/osl-incubator/semantic-release-pr-title-check)
- [X] satellite-weather-downloader, is a system for downloading, transforming and analysing Copernicus weather data using Xarray. It consists in two major apps, satellite_downloader and satellite_weather. [Repository](https://github.com/osl-incubator/satellite-weather-downloader)
- [X] CrawlClima. This package contains the PEGATWEETS and PEGATEMPERATURA modules for automatically capturing tweets and weather data. [Repository](https://github.com/osl-incubator/CrawlClima)
- [ ] dowloader-app. A shapefiles downloader. [Repository](https://github.com/osl-incubator/downloader-app)
- [ ] conda-forge-warning. Conda-Forge Warning aims to present conda-forge package without maintenance. [Repository](https://github.com/osl-incubator/conda-forge-warning)
- [ ] pyreaddbc, is a Python library for working with DBase database file. Legacy systems from the Brazilian Ministry of Health still uses DBF and DBC formats to Publicize data. [Repository](https://github.com/osl-incubator/pyreaddbc)
- [ ] ghreport. A GitHub Report tool. [Repository](https://github.com/osl-incubator/ghreport)
- [ ] gh-check-pr-is-updated. This GitHub actions aims to check if the current PR's branch is updated on top of the upstream branch. [Repository](https://github.com/osl-incubator/gh-check-pr-is-updated)
- [ ] github-actions-self-hosted-runner. Dockerfile for the creation of a GitHub Actions runner image to be deployed dynamically. [Repository](https://github.com/osl-incubator/github-actions-self-hosted-runner)
- [ ] fqlearn. A graphic solver tool to teach mass transfer and thermodynamics.[Repository](https://github.com/osl-pocs/mass-transfer-py)
- [ ] pydatastructs. A project that aims to be a Python package for various data structures and algorithms (including their parallel implementations).[Repository](https://github.com/codezonediitj/pydatastructs/)

### Code of Conduct

- [X] I have read the [Code of Conduct](https://opensciencelabs.github.io/coc/coc-es.html) and I agree.

**Comment by EverVino** [comment]
Hi @AYOHTEE !

Thanks for applying!

We are reviewing your application and we will answer in 1 week after the application deadline.
We will be grateful if you send us your CV to the [opensciencelabs@gmail.com](mailto:opensciencelabs@gmail.com) email, so we can see which project best fits you.

Thank you!

**Comment by EverVino** [comment]
Hi! @AYOHTEE  We have reviewed your application, thank you for applying. We have a few questions before we continue.
We welcome applicants from all levels of programming experience. Whether you're a coding enthusiast or just getting started, we'd love to know more about your background. Can you tell us if you have any experience with programming or if you've used any programming languages before? Feel free to share any related projects or experiences you've had, big or small. It will be great as well if you share with us availability. Tell us how many hours per week you can dedicate to the internship,  and if you have any preferred start and end dates, please let us know. This information will help us tailor the internship experience suits your needs. Thanks

**Comment by EverVino** [comment]
Dear @AYOHTEE,

Thank you for your application to the Open Science Labs Internship Program.

We're excited to share that we've completed our selection process. You will receive an email from us tomorrow with the results.

Thank you for being part of our process.
