### ISSUE TITLE
Internship Apply KRITIKA VERMA

### ISSUE THREAD

**Issue by SunSummoner** [OpenScienceLabs/request-forms#31]
### E-mail

kritikaverma2707@gmail.com

### Full Name

Kritika Verma 

### URL perfil Linkedin

https://www.linkedin.com/in/kritika-verma-0b5394229/

### Bio

I am a highly motivated undergraduate student pursuing a Bachelor of Technology (B. Tech) in Information Technology and Mathematical Innovation with a minor in Computational Biology at Cluster Innovation Centre, University of Delhi. With a strong academic record and a passion for interdisciplinary research, I am dedicated to the fields of mathematical computational modeling, open-source software development, and bioinformatics.
My current research internship at JRaviLab in Aurora, Colorado, has allowed me to engage in cutting-edge antimicrobial resistance research. I specialize in data analysis using Python, drug network creation, and I'm eager to apply machine learning techniques to advance our research further. I have a track record of collaborating within multidisciplinary teams and presenting progress effectively.
In addition to my academic pursuits, I have worked on various projects involving mathematical modeling, numerical analysis, and data visualization. I am proficient in a range of programming languages, including Python, R, MATLAB, and have experience with Git, GitHub, and other technical tools.
My diverse skill set, coupled with a deep interest in scientific machine learning, mathematical programming, and data analysis, positions me well for a future in computational biology and data-driven research. I am enthusiastic about contributing to the open-source community and continuously expanding my knowledge in these fields.

### Send your CV

- [X] I have sent my CV to opensciencelabs@gmail.com

### What projects are you interested in?

- [X] scicookie, is a template developed by Open Science Labs that creates projects from project templates and is based on Cookieninja A Cookiecutter Fork command-line utility. [Repository](https://github.com/osl-incubator/scicookie)
- [X] makim, is based on make and focus on improve the way to define targets and dependencies. Instead of using the Makefile format, it uses yaml format [Repository](https://github.com/osl-incubator/makim)
- [X] containers-sugar. The idea of this project is to organize your stack of containers, gathering some useful scripts and keeping this information centralized in a configuration file. So the command line would be very simple. [Repository](https://github.com/osl-incubator/containers-sugar)
- [X] github-actions-chatgpt-pr-reviewer. This GitHub actions uses OpenAI ChatGPT in order to review the changes presented in a PR and will recommend improvements. [Repository](https://github.com/osl-incubator/github-actions-chatgpt-pr-reviewer)
- [ ] semantic-release-pr-title-check. Checks for Angular commit message format in the Pull Request Title. [Repository](https://github.com/osl-incubator/semantic-release-pr-title-check)
- [X] satellite-weather-downloader, is a system for downloading, transforming and analysing Copernicus weather data using Xarray. It consists in two major apps, satellite_downloader and satellite_weather. [Repository](https://github.com/osl-incubator/satellite-weather-downloader)
- [X] CrawlClima. This package contains the PEGATWEETS and PEGATEMPERATURA modules for automatically capturing tweets and weather data. [Repository](https://github.com/osl-incubator/CrawlClima)
- [ ] dowloader-app. A shapefiles downloader. [Repository](https://github.com/osl-incubator/downloader-app)
- [ ] conda-forge-warning. Conda-Forge Warning aims to present conda-forge package without maintenance. [Repository](https://github.com/osl-incubator/conda-forge-warning)
- [X] pyreaddbc, is a Python library for working with DBase database file. Legacy systems from the Brazilian Ministry of Health still uses DBF and DBC formats to Publicize data. [Repository](https://github.com/osl-incubator/pyreaddbc)
- [X] ghreport. A GitHub Report tool. [Repository](https://github.com/osl-incubator/ghreport)
- [X] gh-check-pr-is-updated. This GitHub actions aims to check if the current PR's branch is updated on top of the upstream branch. [Repository](https://github.com/osl-incubator/gh-check-pr-is-updated)
- [X] github-actions-self-hosted-runner. Dockerfile for the creation of a GitHub Actions runner image to be deployed dynamically. [Repository](https://github.com/osl-incubator/github-actions-self-hosted-runner)
- [X] fqlearn. A graphic solver tool to teach mass transfer and thermodynamics.[Repository](https://github.com/osl-pocs/mass-transfer-py)
- [X] pydatastructs. A project that aims to be a Python package for various data structures and algorithms (including their parallel implementations).[Repository](https://github.com/codezonediitj/pydatastructs/)

### Code of Conduct

- [X] I have read the [Code of Conduct](https://opensciencelabs.github.io/coc/coc-es.html) and I agree.

**Comment by EverVino** [comment]
Hi @SunSummoner !

Thanks for applying!

We are reviewing your application and we will answer in 1 week after the application deadline.

Thank you!

**Comment by SunSummoner** [comment]
Hello @EverVino 

Thank you for informing me and reviewing my application. Please let me know if you require any  other details. I look forward to hearing from you!

**Comment by EverVino** [comment]
Hi! @SunSummoner  We have reviewed your application, thank you for applying. We have a few questions before we continue.
We understand that everyone has a unique schedule, and we want to make sure the internship can work for you. Could share your availability with us? Tell us how many hours per week you can dedicate to the internship, if you have any preferred start and end dates, please let us know. This information will help us tailor the internship experience suits your needs.

**Comment by SunSummoner** [comment]
Hi @EverVino 
Thank you for your response. I will be able to dedicate 15-20 hours per week for this internship. Can I ask what is the earliest and latest I can start? 
Thank you

**Comment by EverVino** [comment]
Dear @SunSummoner,

Thank you for your application to the Open Science Labs Internship Program.

We're excited to share that we've completed our selection process. You will receive an email from us tomorrow with the results.

Your patience and interest are greatly appreciated. If you have questions, contact us at opensciencelabs@gmail.com

Thank you for being part of our process.
