### ISSUE TITLE
Internship Apply Paulo Tintaya

### ISSUE THREAD

**Issue by tintayadev** [OpenScienceLabs/request-forms#34]
### E-mail

pau.tintaya.code@gmail.com

### Full Name

Paulo Emanuel Tintaya Conde

### URL perfil Linkedin

https://www.linkedin.com/in/paulotintaya/

### Bio

Experienced Back-End Web Developer with a passion for mentoring and a love for Python and Django. I thrive on turning ideas into robust, scalable web applications. Whether it's crafting efficient code, guiding the next generation of developers, or solving complex challenges.

### Send your CV

- [X] I have sent my CV to opensciencelabs@gmail.com

### What projects are you interested in?

- [X] scicookie, is a template developed by Open Science Labs that creates projects from project templates and is based on Cookieninja A Cookiecutter Fork command-line utility. [Repository](https://github.com/osl-incubator/scicookie)
- [ ] makim, is based on make and focus on improve the way to define targets and dependencies. Instead of using the Makefile format, it uses yaml format [Repository](https://github.com/osl-incubator/makim)
- [ ] containers-sugar. The idea of this project is to organize your stack of containers, gathering some useful scripts and keeping this information centralized in a configuration file. So the command line would be very simple. [Repository](https://github.com/osl-incubator/containers-sugar)
- [X] github-actions-chatgpt-pr-reviewer. This GitHub actions uses OpenAI ChatGPT in order to review the changes presented in a PR and will recommend improvements. [Repository](https://github.com/osl-incubator/github-actions-chatgpt-pr-reviewer)
- [ ] semantic-release-pr-title-check. Checks for Angular commit message format in the Pull Request Title. [Repository](https://github.com/osl-incubator/semantic-release-pr-title-check)
- [ ] satellite-weather-downloader, is a system for downloading, transforming and analysing Copernicus weather data using Xarray. It consists in two major apps, satellite_downloader and satellite_weather. [Repository](https://github.com/osl-incubator/satellite-weather-downloader)
- [ ] CrawlClima. This package contains the PEGATWEETS and PEGATEMPERATURA modules for automatically capturing tweets and weather data. [Repository](https://github.com/osl-incubator/CrawlClima)
- [X] dowloader-app. A shapefiles downloader. [Repository](https://github.com/osl-incubator/downloader-app)
- [X] conda-forge-warning. Conda-Forge Warning aims to present conda-forge package without maintenance. [Repository](https://github.com/osl-incubator/conda-forge-warning)
- [X] pyreaddbc, is a Python library for working with DBase database file. Legacy systems from the Brazilian Ministry of Health still uses DBF and DBC formats to Publicize data. [Repository](https://github.com/osl-incubator/pyreaddbc)
- [X] ghreport. A GitHub Report tool. [Repository](https://github.com/osl-incubator/ghreport)
- [ ] gh-check-pr-is-updated. This GitHub actions aims to check if the current PR's branch is updated on top of the upstream branch. [Repository](https://github.com/osl-incubator/gh-check-pr-is-updated)
- [X] github-actions-self-hosted-runner. Dockerfile for the creation of a GitHub Actions runner image to be deployed dynamically. [Repository](https://github.com/osl-incubator/github-actions-self-hosted-runner)
- [ ] fqlearn. A graphic solver tool to teach mass transfer and thermodynamics.[Repository](https://github.com/osl-pocs/mass-transfer-py)
- [X] pydatastructs. A project that aims to be a Python package for various data structures and algorithms (including their parallel implementations).[Repository](https://github.com/codezonediitj/pydatastructs/)

### Code of Conduct

- [X] I have read the [Code of Conduct](https://opensciencelabs.github.io/coc/coc-es.html) and I agree.

**Comment by EverVino** [comment]
Hi! @tintayadev  We have reviewed your application, thank you for applying. We have a few questions before we continue.
We understand that everyone has a unique schedule, and we want to make sure the internship can work for you. Could share your availability with us? Tell us how many hours per week you can dedicate to the internship, and if you have any preferred start and end dates, please let us know. This information will help us tailor the internship experience suits your needs.

**Comment by tintayadev** [comment]
Hey there, thank you so much for considering my application. Regarding my availability for the internship. I'm currently a university student, so I won't be able to commit to a full-time schedule. However, I can dedicate 15 hours per week(3-4 hours per day). But I'm also open to increase my time if needed to meet the internship requirements. I would prefer to start the internship in mid-November if possible, and I'm flexible with the end date, willing to continue as long as needed. Please let me know if it's possible to work with this schedule, and once again thank you so much.

**Comment by EverVino** [comment]
Dear @tintayadev  ,

Thank you for your application to the Open Science Labs Internship Program.

We're excited to share that we've completed our selection process.  We have taken into account your time availability. You will receive an email from us tomorrow with the results.

Your patience and interest are greatly appreciated. If you have questions, contact us at opensciencelabs@gmail.com

Thank you for being part of our process.
