### ISSUE TITLE
Ervin Adrian Duran Aguilar

### ISSUE THREAD

**Issue by ErvinDuran** [OpenScienceLabs/request-forms#35]
### E-mail

ervinduran4@gmail.com

### Nombre Completo

Ervin Adrian Duran Aguilar

### URL de foto de perfil

https://scontent.flpb2-1.fna.fbcdn.net/v/t1.6435-9/46891334_2168709566507561_3067255000427134976_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=be3454&_nc_ohc=NJ8bAQKU7WUAX9J3ZC4&_nc_ht=scontent.flpb2-1.fna&oh=00_AfBzysi-UiMvf3dh166RIa04w4kdmOO7fP1eLyckuKj5VA&oe=65579C85

### Idiomas

Español, Inglés

### Bio

Soy egresado de la carrera de ingeniería ambiental, apasionado por la programación y sistemas de información geográfica, en camino hacia el modelamiento como calidad de agua y climatología, los mismos me llevaron por el camino del análisis estadístico de datos, también disfruto mucho del ciclismo y natación.

### ¿Por qué quiero colaborar a la comunidad OSL?

Siempre he disfrutado de la investigación científica, el intercambio de conocimientos y formar parte de un grupo que ayude en el avance tecnológico y científico, todo esto me impulsa a querer formar parte de OSL.

### Área de interés

DevOps, Creación de Artículos (blog), Community Management, Social Media, Mentoría, Gestión de Proyectos

### Horas semanales disponibles para dedicarme a la comunidad OSL

4 horas semanales

### Código de Conducta

- [X] He leído el [Código de Conducta](https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo

### Guía de Mentorías

- [X] He leído la [Guía de Mentorías](https://opensciencelabs.github.io/mentoring/guide-en.html)

**Comment by xmnlab** [comment]
@ErvinDuran , gracias por tu interés en participar en la comunidad OSL.
perdón la tardanza en darte una actualización aquí.

Tienes tiempo esta semana para una reunión online para discutir este tema?

muchas gracias

**Comment by xmnlab** [comment]
@ErvinDuran , un recuerdo amistoso sobre esta solicitud :)

**Comment by xmnlab** [comment]
@ErvinDuran , como no hemos escuchado de ti en estas dos última semanas, voy a cerrar esta solicitud.
si aún estás interesado, esté a gusto de reabrir esta issue y seguimos la discusión y coordinamos una reunión para empezar.

muchas gracias
