### ISSUE TITLE
Internship Apply GABRIELA SALAS CABRERA

### ISSUE THREAD

**Issue by gabrielasc95** [OpenScienceLabs/request-forms#37]
### E-mail

salascabrerag@gmail.com

### Full Name

GABRIELA SALAS CABRERA

### URL perfil Linkedin

https://www.linkedin.com/in/gabriela-salas-cabrera-7b8554130/

### Bio

[CV_GABRIELA_SALAS_CABRERA.pdf](https://github.com/OpenScienceLabs/request-forms/files/13233727/CV_GABRIELA_SALAS_CABRERA.pdf)

### Send your CV

- [X] I have sent my CV to opensciencelabs@gmail.com

### What projects are you interested in?

- [X] scicookie, is a template developed by Open Science Labs that creates projects from project templates and is based on Cookieninja A Cookiecutter Fork command-line utility. [Repository](https://github.com/osl-incubator/scicookie)
- [X] makim, is based on make and focus on improve the way to define targets and dependencies. Instead of using the Makefile format, it uses yaml format [Repository](https://github.com/osl-incubator/makim)
- [X] containers-sugar. The idea of this project is to organize your stack of containers, gathering some useful scripts and keeping this information centralized in a configuration file. So the command line would be very simple. [Repository](https://github.com/osl-incubator/containers-sugar)
- [X] github-actions-chatgpt-pr-reviewer. This GitHub actions uses OpenAI ChatGPT in order to review the changes presented in a PR and will recommend improvements. [Repository](https://github.com/osl-incubator/github-actions-chatgpt-pr-reviewer)
- [X] semantic-release-pr-title-check. Checks for Angular commit message format in the Pull Request Title. [Repository](https://github.com/osl-incubator/semantic-release-pr-title-check)
- [X] satellite-weather-downloader, is a system for downloading, transforming and analysing Copernicus weather data using Xarray. It consists in two major apps, satellite_downloader and satellite_weather. [Repository](https://github.com/osl-incubator/satellite-weather-downloader)
- [X] CrawlClima. This package contains the PEGATWEETS and PEGATEMPERATURA modules for automatically capturing tweets and weather data. [Repository](https://github.com/osl-incubator/CrawlClima)
- [X] dowloader-app. A shapefiles downloader. [Repository](https://github.com/osl-incubator/downloader-app)
- [X] conda-forge-warning. Conda-Forge Warning aims to present conda-forge package without maintenance. [Repository](https://github.com/osl-incubator/conda-forge-warning)
- [X] pyreaddbc, is a Python library for working with DBase database file. Legacy systems from the Brazilian Ministry of Health still uses DBF and DBC formats to Publicize data. [Repository](https://github.com/osl-incubator/pyreaddbc)
- [X] ghreport. A GitHub Report tool. [Repository](https://github.com/osl-incubator/ghreport)
- [X] gh-check-pr-is-updated. This GitHub actions aims to check if the current PR's branch is updated on top of the upstream branch. [Repository](https://github.com/osl-incubator/gh-check-pr-is-updated)
- [X] github-actions-self-hosted-runner. Dockerfile for the creation of a GitHub Actions runner image to be deployed dynamically. [Repository](https://github.com/osl-incubator/github-actions-self-hosted-runner)
- [X] fqlearn. A graphic solver tool to teach mass transfer and thermodynamics.[Repository](https://github.com/osl-pocs/mass-transfer-py)
- [X] pydatastructs. A project that aims to be a Python package for various data structures and algorithms (including their parallel implementations).[Repository](https://github.com/codezonediitj/pydatastructs/)

### Code of Conduct

- [X] I have read the [Code of Conduct](https://opensciencelabs.github.io/coc/coc-es.html) and I agree.

**Comment by xmnlab** [comment]
dear @gabrielasc95 , thanks for your interesting on this internship program.

Currently, the call for internship is already close for this cycle, we will open a call for the next cycle of internship in the beginning of next year.

For next cycle, we should have a new list of projects affiliated, so please stay tuned for more updates.

If you want to discuss and learn more about the program and the projects we have, we can have an online meeting as well.

All the best,

**Comment by xmnlab** [comment]
@gabrielasc95 the call for intern is already open: https://opensciencelabs.org/blog/call-for-interns-2024-01

hope to see you around!
all the best!
