### ISSUE TITLE
New Mentor: GABRIELA SALAS CABRERA

### ISSUE THREAD

**Issue by gabrielasc95** [OpenScienceLabs/request-forms#38]
### E-mail

salascabrerag@gmail.com

### Nombre Completo

GABRIELA SALAS CABRERA

### URL perfil Linkedin

https://www.linkedin.com/in/gabriela-salas-cabrera-7b8554130/

### URL de foto de perfil

https://drive.google.com/file/d/1TLcevbvjhGFf_-ay3Ip_3_7hYmnLZMSm/view

### Bio

[CV_GABRIELA_SALAS_CABRERA.pdf](https://github.com/OpenScienceLabs/request-forms/files/13233802/CV_GABRIELA_SALAS_CABRERA.pdf)

### Áreas de interés para las mentorías

CIENCIA DE DATOS, PROGRAMACION, ALGORITMOS

### Idiomas

Español, Inglés

### Cupos disponibles

10

### Código de Conducta

- [X] He leído el [Código de Conducta](https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo

### Guía de Mentorías

- [X] He leído la [Guía de Mentorías](https://opensciencelabs.github.io/mentoring/guide-en.html)

**Comment by xmnlab** [comment]
Hola @gabrielasc95 
Gracias por tu interés en ser parte del programa de mentorías.
Tienes tiempo esta semana o la próxima para una reunión online para discutir este tema?

un feliz día,

**Comment by gabrielasc95** [comment]
Buenas tardes ¿que le parece en la siguiente semana? estaré libre
saludos excelente día

**Comment by EverVino** [comment]
Hola @gabrielasc95 podrias llenar tus horas libres -> https://www.when2meet.com/?22284437-kePiA para quedar una hora esta semana. Muchas gracias

**Comment by gabrielasc95** [comment]
Listo ya registré mis horas libres

**Comment by EverVino** [comment]
@gabrielasc95 Ya envié la invitación de reunión a tu email para el dia sábado a las 10:00 hora mexico  Nos vemos ahi. Ten un buen día

**Comment by xmnlab** [comment]
Me imagino que ya podemos cerrar esta issue.
bienvenida @gabrielasc95 !
muchas gracias @gabrielasc95 y @EverVino
