### ISSUE TITLE
Internship Apply Ines Sanchez-Rodriguez

### ISSUE THREAD

**Issue by incsanchezro** [OpenScienceLabs/request-forms#39]
### E-mail

incsanchezro@gmail.com

### Full Name

Ines Sanchez-Rodriguez

### URL perfil Linkedin

https://www.linkedin.com/in/ines-sanchez-rodriguez-ella-she-her-2022061a7/

### Bio

Ines is a PhD student at the University of Saskatchewan, Canada, driven to understand the relationship between humans and the hydrological cycle. Her research philosophy is guided by open collaboration. Participatory hydrological modeling has significantly engaged with watershed partners, bridging the gap between science and the public. However, open collaboration requires models that deliberately integrate the basin's knowledge diversity and people agencies. Failure to meet these conditions will marginalize communities during water resource decisions, excluding their valuable knowledge. Open collaboration is also crucial for achieving sustainability, which Ines strives to embody as a woman, researcher, and computer modeller.

Ines has collaborated with meteorological and conservation agencies, contributing to global projects like earth2observe. She is skilled in assessing water ecosystem services and creating natural resource-based climate adaptation solutions. Her experience in the field has inspired her to apply computational hydrological models for ecosystem conservation strategies.
Ines is a Python programmer with beginner to medium experience. She regularly uses Python for research scripts and contributed to the development of Jaziku, a statistical tool for inferring climatological teleconnections (visit: https://github.com/XavierCLL/Jaziku).

In addition to her studies and research, Ines serves as the chair of the Global Institute for Water Security students and Yourg Reserachers group (GIWS-SYR). She is an activist for causes like the Climate Reality Project in Saskatoon and Voices for Science of the American Geoscience Union. In her free time, she enjoys biking and exploring new paths. Art movies that challenge conventions inspire her, while mindfulness practices and hero's journey literature fuel her personal growth.

### Send your CV

- [ ] I have sent my CV to opensciencelabs@gmail.com

### What projects are you interested in?

- [ ] scicookie, is a template developed by Open Science Labs that creates projects from project templates and is based on Cookieninja A Cookiecutter Fork command-line utility. [Repository](https://github.com/osl-incubator/scicookie)
- [ ] makim, is based on make and focus on improve the way to define targets and dependencies. Instead of using the Makefile format, it uses yaml format [Repository](https://github.com/osl-incubator/makim)
- [ ] containers-sugar. The idea of this project is to organize your stack of containers, gathering some useful scripts and keeping this information centralized in a configuration file. So the command line would be very simple. [Repository](https://github.com/osl-incubator/containers-sugar)
- [X] github-actions-chatgpt-pr-reviewer. This GitHub actions uses OpenAI ChatGPT in order to review the changes presented in a PR and will recommend improvements. [Repository](https://github.com/osl-incubator/github-actions-chatgpt-pr-reviewer)
- [ ] semantic-release-pr-title-check. Checks for Angular commit message format in the Pull Request Title. [Repository](https://github.com/osl-incubator/semantic-release-pr-title-check)
- [X] satellite-weather-downloader, is a system for downloading, transforming and analysing Copernicus weather data using Xarray. It consists in two major apps, satellite_downloader and satellite_weather. [Repository](https://github.com/osl-incubator/satellite-weather-downloader)
- [X] CrawlClima. This package contains the PEGATWEETS and PEGATEMPERATURA modules for automatically capturing tweets and weather data. [Repository](https://github.com/osl-incubator/CrawlClima)
- [X] dowloader-app. A shapefiles downloader. [Repository](https://github.com/osl-incubator/downloader-app)
- [ ] conda-forge-warning. Conda-Forge Warning aims to present conda-forge package without maintenance. [Repository](https://github.com/osl-incubator/conda-forge-warning)
- [ ] pyreaddbc, is a Python library for working with DBase database file. Legacy systems from the Brazilian Ministry of Health still uses DBF and DBC formats to Publicize data. [Repository](https://github.com/osl-incubator/pyreaddbc)
- [X] ghreport. A GitHub Report tool. [Repository](https://github.com/osl-incubator/ghreport)
- [ ] gh-check-pr-is-updated. This GitHub actions aims to check if the current PR's branch is updated on top of the upstream branch. [Repository](https://github.com/osl-incubator/gh-check-pr-is-updated)
- [ ] github-actions-self-hosted-runner. Dockerfile for the creation of a GitHub Actions runner image to be deployed dynamically. [Repository](https://github.com/osl-incubator/github-actions-self-hosted-runner)
- [ ] fqlearn. A graphic solver tool to teach mass transfer and thermodynamics.[Repository](https://github.com/osl-pocs/mass-transfer-py)
- [ ] pydatastructs. A project that aims to be a Python package for various data structures and algorithms (including their parallel implementations).[Repository](https://github.com/codezonediitj/pydatastructs/)

### Code of Conduct

- [X] I have read the [Code of Conduct](https://opensciencelabs.github.io/coc/coc-es.html) and I agree.

**Comment by xmnlab** [comment]
hi @incsanchezro !

It is a pleasure to receive your application here. 
The current internship cycle has already started, but the next cycle will start in the beginning of next year: https://opensciencelabs.org/programs/internship/

so please, stay tuned!

Also, the available projects for the next cycle are not selected yet. Additionally, the format of the internship for next cycles is a bit different, so I highly recommend you to check our documentation about the internship in the link above.

Feel free to reach me out if you have any questions, also I am available for online calls if you want, just le mt know.

All the best,

**Comment by xmnlab** [comment]
@incsanchezro the call for intern is already open: https://opensciencelabs.org/blog/call-for-interns-2024-01

hope to see you around!
all the best!
