### ISSUE TITLE
Solicitud de mentoría: <Anahi Castillo>

### ISSUE THREAD

**Issue by AnahiCastillo** [OpenScienceLabs/request-forms#40]
### E-mail

anahivivianac@gmail.com

### Nombre Completo

Anahi Viviana Castillo Condori

### Las(os) Mentoras(os)

Evelyn

### Expectativas

Me interesa que la mentoría pueda orientarme y guiarme para un sistema dlp con software libre. 

### Horario de la Primera Reunión

Lunes a las 9

### URL perfil Linkedin

. 

### URL perfil Twitter

. 

### URL perfil GitHub

. 

### Código de Conducta

- [X] He leído el [Código de Conducta](https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo

### Guía de Mentorías

- [X] He leído la [Guía de Mentorías](https://opensciencelabs.github.io/mentoring/guide-en.html)

**Comment by xmnlab** [comment]
@AnahiCastillo,

gracias por tu solicitud. 

voy a contactar a la mentora y me comunico de vuelta contigo pronto.

**Comment by EverVino** [comment]
@AnahiCastillo, mil disculpas por la tardanza en responder. En este momento la mentora no se encuentra disponible. No quisieras tener algun otro mentor? https://opensciencelabs.org/programs/mentoring/mentors/
Voy a estar atento a tu respuesta.

**Comment by EverVino** [comment]
Hola @AnahiCastillo estoy cerrando esta issue. Sientete libre de reabrirla cuando asi lo necesites.
