### ISSUE TITLE
OSL Internship Program 2024-01 (Orgs/Projects): PyDataStructs

### ISSUE THREAD

**Issue by czgdp1807** [OpenScienceLabs/request-forms#43]
### Organization/Project Name

PyDataStructs

### Organization/Project Webpage URL

https://pydatastructs.readthedocs.io/en/latest/

### Organization/Project Introduction

PyDataStructs project aims to be a Python package for various data structures and algorithms (including their parallel implementations). 

### Organization/Project Summary

* Single package for all your data structures and algorithms

* Consistent and Clean Interface - The APIs we have provided are consistent with each other, clean, and easy to use. We make sure of that before adding any new data structure or algorithm.

* Well Tested - We thoroughly test our code before making any new addition to PyDataStructs. 99 percent lines of our code have already been tested by us

### Organization/Project Structure

Maintainer - Gagandeep Singh (@czgdp1807)

### Applicant's Full Name

Gagandeep Singh

### Applicant's Email

gdp.1807@gmail.com

### Code of Conduct Agreement

- [X] I have read and agree to the
[Code of Conduct](https://opensciencelabs.org/guidelines/coc/).

### Project Ideas Document Link

https://github.com/codezonediitj/pydatastructs/wiki/Planned-Features-for-v1.0.1

**Comment by xmnlab** [comment]
Thank you @czgdp1807  for submitting your application to our internship program.
We're pleased to inform you that your application is complete and in excellent condition.
Our team will review it and get back to you shortly with further details.

We appreciate your interest in joining our program.
All the best,

**Comment by xmnlab** [comment]
PyDataStructs is already listed:

* OSL Internship page https://opensciencelabs.org/programs/internship/cycles/2024-01/#pydatastructs
* Announcement Blog Post https://opensciencelabs.org/blog/call-for-interns-2024-01/#pydatastructs

Thank you @czgdp1807
