### ISSUE TITLE
OSL Internship Program 2024-01 (Orgs/Projects): Makim

### ISSUE THREAD

**Issue by xmnlab** [OpenScienceLabs/request-forms#44]
### Organization/Project Name

Makim

### Organization/Project Webpage URL

https://osl-incubator.github.io/makim/

### Organization/Project Introduction

Makim (or just makim) is based on make and focus on improve the way to define targets and dependencies. Instead of using the Makefile format, it uses yaml format.

### Organization/Project Summary

Makim aims to offer a way to define targets and dependencies with some special control options, like conditionals if, etc.

Some Key Features:

* Help text as first-class in the .makim.yaml specification. It can be used by targets and arguments.
* Targets have an option for arguments.
* Targets have an option for dependencies.
* Dependencies can call a target with specific arguments.
* Dependencies can have a conditional control flow (if).
* Allow the creation of groups, so the targets can be organized by topics.
* Targets and groups have an option for user defined variables and/or environment variables.
* Access arguments, variables or environment variables via template (using Jinja2).
* Option for using dot environment files using env-file key.

### Organization/Project Structure

Makim is under the OSL Incubator Program

### Applicant's Full Name

Ivan Ogasawara

### Applicant's Email

ivan.ogasawara@gmail.com

### Code of Conduct Agreement

- [X] I have read and agree to the
[Code of Conduct](https://opensciencelabs.org/guidelines/coc/).

### Project Ideas Document Link

https://github.com/osl-incubator/makim/issues/74

**Comment by EverVino** [comment]
@xmnlab  thank you for applying to the internship project program.
We're pleased to inform you that your application is complete and in excellent condition.
Our team will review it and get back to you shortly with further details.

We appreciate your interest in joining our program.
All the best.

**Comment by xmnlab** [comment]
Makim is already listed:

* OSL Internship page https://opensciencelabs.org/programs/internship/cycles/2024-01/#makim
* Announcement Blog Post https://opensciencelabs.org/blog/call-for-interns-2024-01/#makim
