### ISSUE TITLE
OSL Internship Program 2024-01 (Orgs/Projects): Sugar

### ISSUE THREAD

**Issue by xmnlab** [OpenScienceLabs/request-forms#45]
### Organization/Project Name

Sugar

### Organization/Project Webpage URL

https://osl-incubator.github.io/sugar/

### Organization/Project Introduction

Sugar aims to organize your stack of containers, gathering some useful scripts and keeping this information centralized in a configuration file. So the command line would be very simple.

### Organization/Project Summary

Sugar is a utility designed to streamline the use of container technologies like Docker. It primarily focuses on reducing the complexity and repetitive nature of using `docker-compose`, especially when dealing with multiple projects and additional parameters.

**Key Features:**

- **Integration with docker-compose:** Sugar supports various `docker-compose` commands (e.g., build, up, down, logs) directly, eliminating the need for extra parameters.
- **Extended Commands:** A set of extended commands (e.g., start, restart) are provided through the `ext` profile/plugin, enhancing functionality.
- **Config File Management:** Project-specific configurations are centralized in a `.sugar.yaml` file, simplifying command-line usage and project organization.
- **Group and Service Management:** Allows defining groups and services in the configuration file, facilitating targeted operations on specific sets of containers.

### Organization/Project Structure

Sugar is a project under the Open Science Labs incubator Program

### Applicant's Full Name

Ivan Ogasawara

### Applicant's Email

ivan.ogasawara@gmail.com

### Code of Conduct Agreement

- [X] I have read and agree to the
[Code of Conduct](https://opensciencelabs.org/guidelines/coc/).

### Project Ideas Document Link

https://github.com/osl-incubator/sugar/issues/105

**Comment by EverVino** [comment]
@xmnlab  thank you for applying to the internship project program.
We're pleased to inform you that your application is complete and in excellent condition.
Our team will review it and get back to you shortly with further details.

We appreciate your interest in joining our program.
All the best.

**Comment by xmnlab** [comment]
Sugar is already listed:

* OSL Internship page https://opensciencelabs.org/programs/internship/cycles/2024-01/#sugar
* Announcement Blog Post https://opensciencelabs.org/blog/call-for-interns-2024-01/#sugar
