### ISSUE TITLE
OSL Internship Program 2024-01 (Orgs/Projects): Envers

### ISSUE THREAD

**Issue by xmnlab** [OpenScienceLabs/request-forms#46]
### Organization/Project Name

Envers

### Organization/Project Webpage URL

https://osl-incubator.github.io/envers/

### Organization/Project Introduction

Envers is a command-line tool (CLI) designed to manage and version environment variables for different deployment stages such as staging, development, and production. It provides a secure and organized way to handle environment-specific configurations.

### Organization/Project Summary

Key Features:

* Encrypt environment variables: Creates encrypted files that store environment variables that can be safely stored in a git repository
* Group-Based Configurations: Allows defining variables for different groups/profiles like prod, dev, etc.
* File-Based Variable Definitions: Supports multiple environment files (.env) with specific variables for each file.
* CLI-Driven: Provide CLI commands that helps to create drafts for environment variables and deploy it to encrypted files
* Spec Management: Each release has a defined spec that applies to all groups/profiles within that release.
* Environment File Generation: Enables generating .env files for specific versions and groups/profiles using commands.

### Organization/Project Structure

Envers is under the Open Science Labs Incubator Program

### Applicant's Full Name

Ivan Ogasawara

### Applicant's Email

ivan.ogasawara@gmail.com

### Code of Conduct Agreement

- [X] I have read and agree to the
[Code of Conduct](https://opensciencelabs.org/guidelines/coc/).

### Project Ideas Document Link

https://github.com/osl-incubator/envers/issues/18

**Comment by EverVino** [comment]
@xmnlab  thank you for applying to the internship project program.
We're pleased to inform you that your application is complete and in excellent condition.
Our team will review it and get back to you shortly with further details.

We appreciate your interest in joining our program.
All the best.

**Comment by xmnlab** [comment]
Envers is already listed:

* OSL Internship page https://opensciencelabs.org/programs/internship/cycles/2024-01/#envers
* Announcement Blog Post https://opensciencelabs.org/blog/call-for-interns-2024-01/#envers
