### ISSUE TITLE
OSL Internship Program 2024-01 (Orgs/Projects): SciCookie

### ISSUE THREAD

**Issue by xmnlab** [OpenScienceLabs/request-forms#47]
### Organization/Project Name

SciCookie

### Organization/Project Webpage URL

https://osl-incubator.github.io/scicookie

### Organization/Project Introduction

SciCookie is a template developed by https://opensciencelabs.org/ that creates projects from project templates.

### Organization/Project Summary

Key Features:

* Licenses supported: MIT, BSD 3 Clause, ISC License, Apache Software License 2.0, and GPL 3
* Documentation engines: mkdocs, sphinx, jupyter-boook
* Test library: pytest, hypothesis
* Auto format code tool: blue and black
* Initial integration with git
* Support to conda (as base environment) and poetry as packaging and dependency management
* Support to pre-commit
* CI with github actions
* Release workflow with semantic release and github actions
* Flexible build system selection: Choose between popular build systems like [Poetry](https://python-poetry.org/), [Flit](https://flit.pypa.io/), [meson-python](https://meson-python.readthedocs.io/en/latest/index.html), [Setuptools](https://setuptools.pypa.io/en/latest/), [PDM](https://pdm.fming.dev/), [Hatch](https://hatch.pypa.io/), [Maturin](https://pypi.org/project/maturin/0.8.2/), [scikit-build-core](https://scikit-build-core.readthedocs.io/en/latest/) or [setuptools + pybind11](https://pybind11.readthedocs.io/en/stable/) based on your preference.
* The structure of the project can use the src layout or flat layout. The “src layout” moving the code that is intended to be importable into a subdirectory. This subdirectory is typically named src. "Flat layout" refers to organising a project's files in a folder or repository so that the various configuration files and import packages are all in the top-level directory. You can read about their differences at https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/
* Finding common security problems in Python code using [bandit](https://bandit.readthedocs.io/en/latest/)
Offers the option to use [pydocstyle](http://www.pydocstyle.org/en/stable/) for checking compliance with Python documentation conventions.
* Finds unused code in Python programs using [vulture](https://github.com/jendrikseipp/vulture).
* To automatically detect overly complex code based on cyclomatic complexity, the template gives you the option to use the [McCabe](https://github.com/PyCQA/mccabe) library, which is included via flake8.
* Provides the option to add initial files that allow you to run and orchestrate containers using [Docker](https://docs.docker.com/) or [Podman](https://podman.io/) in your project.

### Organization/Project Structure

SciCookie is under the Open Science Labs Incubator Program

### Applicant's Full Name

Ivan Ogasawara

### Applicant's Email

ivan.ogasawara@gmail.com

### Code of Conduct Agreement

- [X] I have read and agree to the
[Code of Conduct](https://opensciencelabs.org/guidelines/coc/).

### Project Ideas Document Link

https://github.com/osl-incubator/scicookie/issues/192

**Comment by EverVino** [comment]
@xmnlab  thank you for applying to the internship project program.
We're pleased to inform you that your application is complete and in excellent condition.
Our team will review it and get back to you shortly with further details.

We appreciate your interest in joining our program.
All the best.

**Comment by xmnlab** [comment]
SciCookie is already listed:

* OSL Internship page https://opensciencelabs.org/programs/internship/cycles/2024-01/#scicookie
* Announcement Blog Post https://opensciencelabs.org/blog/call-for-interns-2024-01/#scicookie
