### ISSUE TITLE
OSL Internship Program 2024-01 (Orgs/Projects): ArtBox

### ISSUE THREAD

**Issue by xmnlab** [OpenScienceLabs/request-forms#48]
### Organization/Project Name

ArtBox

### Organization/Project Webpage URL

https://osl-incubator.github.io/artbox/

### Organization/Project Introduction

ArtBox is a tool set for handling multimedia files with a bunch of useful functions.

### Organization/Project Summary

Key Features:

* Convert text to audio
* Download a youtube video
* Create a song based on the musical notes
* Remove the audio from a video
* Extract the audio from a video
* Combine audio and video files

### Organization/Project Structure

ArtBox is under the Open Science Labs Incubator Program

### Applicant's Full Name

Ivan Ogasawara

### Applicant's Email

ivan.ogasawara@gmail.com

### Code of Conduct Agreement

- [X] I have read and agree to the
[Code of Conduct](https://opensciencelabs.org/guidelines/coc/).

### Project Ideas Document Link

https://github.com/osl-incubator/artbox/issues/10

**Comment by EverVino** [comment]
@xmnlab  thank you for applying to the internship project program.
We're pleased to inform you that your application is complete and in excellent condition.
Our team will review it and get back to you shortly with further details.

We appreciate your interest in joining our program.
All the best.

**Comment by xmnlab** [comment]
ArtBox is already listed:

* OSL Internship page https://opensciencelabs.org/programs/internship/cycles/2024-01/#artbox
* Announcement Blog Post https://opensciencelabs.org/blog/call-for-interns-2024-01/#artbox
