### ISSUE TITLE
New Mentor: Evelyn Donis

### ISSUE THREAD

**Issue by Aledonisgt** [OpenScienceLabs/request-forms#5]
# ¡Convocatoria para Mentores!

Open Science Labs (OSL) es una comunidad que ofrece un espacio abierto para compartir, aprender y enseñar temas relacionados a Ciencia Abierta y Tecnologías computacionales (Python, C++, JavaScript, Machine learning, DevOps, etc) al público de Latinoamérica, pero no restringido a ello. Nuestra comunidad no intenta crear la rueda, sino que queremos integrar con otras comunidades y unir esfuerzos. 

Si quieres ser mentore/a en nuestra comunidad, llene el siguiente formulario:

```{note}
(*) Obligatorio.
```

**E-mail`evydonis@gmail.com`**: 
**Nombre completo`Evelyn Alejandra Donis González`**: 
**Área de interés para las mentorías`Ciberseguridad, Desarrollo Seguro`**:
**https://www.linkedin.com/in/evelyn-donis-4784a0103**:
**URL del perfil en Twitter**:
**URL del perfil en GitHub**:

He leído el [Código de Conducta](https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo`Sí`:
- [x] Sí

He leído la [Guía de Mentorías](https://opensciencelabs.github.io/mentoring/guide-en.html)`Sí`:
- [x] Sí

**Comment by xmnlab** [comment]
@Aledonisgt nos podrías enviar un imagen tuya de perfil o un link de una imagen tuya de perfil?
vamos a crear una página para mentores y te vamos a incluir allá.
también vamos a necesitar una bio tuya para agregar a esta página. 

aquí está una versión inicial para autores de blog posts como ejemplo: https://opensciencelabs.github.io/articles/authors/alan-hurtarte.html

**Comment by Aledonisgt** [comment]
@xmnlab con gusto Ivan, te lo proporciono en el transcurso de hoy.

**Comment by Aledonisgt** [comment]
@xmnlab  te adjunto mi fotografía y breve bio.

Ingeniera en Sistemas y Auditor Líder Certificado en ISO27001 Seguridad de la Información e ISO22301 Continuidad del Negocio. Con más de 12 años de experiencia en seguridad de la información, seguridad informática, así como la realización de auditoría de sistemas y asesoramiento e implementación de sistemas de gestión de continuidad del negocio, gestión de incidentes y plan de continuidad del negocio, gestión de incidentes y plan de recuperación de desastres, para diferentes industrias financieras, telecomunicaciones, manufactureras, entre otras. Cuenta con experiencia en seguridad informática, evaluación, identificación y mitigación de riesgos de acuerdo a la implementación de controles internos en las áreas de TI.  Sus  principales análisis se basan en estructuración, verificación y validación de logs de los sistemas de información, operativos y bases de datos, dentro de los cuales ha podido identificar fraudes informáticos y transaccionales dentro de las organizaciones en las que ha laborado. Así mismo ha realizado análisis de acceso de usuarios a través de la validación de privilegios, roles y segregación de funciones en sistema SAP. Actualmente se desempeña como Consultora Senior en Seguridad de la Información y Ciberseguridad en ES Consulting.
![pry (2)](https://user-images.githubusercontent.com/98857005/152877512-1f664a42-7c91-43df-91aa-af60983f29f6.jpg)


Me cuentas si te sirve esta info.

Saludos,

**Comment by xmnlab** [comment]
@Aledonisgt muchas gracias, las informaciones están perfecta.
he pedido a la persona que pidió la mentoría que pase más informaciones. cuando lo haga, ya daremos secuencia con el tema :)

**Comment by EverVino** [comment]
Hola @Aledonisgt estamos coordinando una nueva reunión, nos podrías indicar tu disponibilidad de tiempo aquí -> https://strawpoll.com/kjz68rgeo (esta pagina nos permite coordinar nuestros tiempos con diferentes zonas horarias).  Gracias

**Comment by xmnlab** [comment]
@Aledonisgt te esperamos en una de nuestras reuniones para darte la bienvenida en vivo :)

**Comment by xmnlab** [comment]
@Aledonisgt , estamos preparando para volver el próximo año con el programa de mentorías. nos gustaría saber si aún estás interesada en colaborar como mentora en OSL. sería un gusto tenerte a boardo. saludos!

**Comment by xmnlab** [comment]
@Aledonisgt siguiendo lo que hemos hablado con discord, ya hemos subido la primera versión de la página de mentoras/es: https://opensciencelabs.org/mentoring/mentors/

esta semana te voy a agregar allá. una consulta, cuántos cupos tendrías disponible para las mentorías?
muchas gracias

**Comment by Aledonisgt** [comment]
Hola!!

Si son sesiones individuales no más de 5, ahora si son en grupo pueden ser
hasta 10.

Saludos,

**Comment by xmnlab** [comment]
hecho! https://opensciencelabs.org/mentoring/mentors/
otra consulta, vamos a incluir en la página los idiomas que cada mentor puede dar las mentorías.
me podrías informar en cuál idiomas podrías dar tus mentorías?

**Comment by xmnlab** [comment]
voy dejar por el momento Español. me avisas si quieres que incluya otro idioma, por favor.
muchas gracias.
