### ISSUE TITLE
OSL Internship Program 2024-01 (Orgs/Projects): OSL-webpage

### ISSUE THREAD

**Issue by EverVino** [OpenScienceLabs/request-forms#50]
### Organization/Project Name

OSL Web Page

### Organization/Project Webpage URL

https://opensciencelabs.org/

### Organization/Project Introduction

OpenScienceLabs web page, is a project that serves as a way to present OSL to the world  through a web page.

### Organization/Project Summary

The Open Science Labs / web page project aims to create a dynamic and user-friendly web platform that serves as a central hub for the Open Science Labs community. This platform will provide essential information about the organization, serve as a knowledge repository, and facilitate communication and collaboration among community members.

### Organization/Project Structure

osl-webpage is main page for OSL 

### Applicant's Full Name

John Ever Vino Duran

### Applicant's Email

evervino00@gmail.com

### Code of Conduct Agreement

- [X] I have read and agree to the
[Code of Conduct](https://opensciencelabs.org/guidelines/coc/).

### Project Ideas Document Link

https://github.com/OpenScienceLabs/opensciencelabs.github.io/issues/84

**Comment by xmnlab** [comment]
@EverVino, thank you for applying to the internship project program.

We're pleased to inform you that your application is complete and in excellent condition.
Our team will review it and get back to you shortly with further details.

We appreciate your interest in joining our program.
All the best.

**Comment by xmnlab** [comment]
OSL Webpage is already listed:

* OSL Internship page https://opensciencelabs.org/programs/internship/cycles/2024-01/#osl-web-page
* Announcement Blog Post https://opensciencelabs.org/blog/call-for-interns-2024-01/#osl-web-page

thanks @EverVino
