### ISSUE TITLE
New Intern: Rafael Nobre

### ISSUE THREAD

**Issue by RafaelNobre21** [OpenScienceLabs/request-forms#54]
### Send your Project Proposal to Open Science Lab email

- [ ] I have sent my Project Proposal to opensciencelabs@gmail.com

### Code of Conduct

- [X] I have read the [Code of Conduct](https://opensciencelabs.org/guidelines/coc/) and I agree.

**Comment by xmnlab** [comment]
thanks @RafaelNobre21 for applying for the OSL Internship Program.

First, check the project from here https://opensciencelabs.org/blog/call-for-interns-2024-01/#list-of-participating-projects. Each project has a few project ideas.

Next, contact its correspondent mentor, who will assign you some few small issues to work on. If you manage to accomplish that, your mentor will ask you to move forward your application here.

You need to write and send a plan for your internship to [opensciencelabs@gmail.com](mailto:opensciencelabs@gmail.com). You can find the template here: https://opensciencelabs.org/programs/internship/templates/intern-proposal/

Feel free to ping me here if you have any questions.

All the best,

**Comment by RafaelNobre21** [comment]
i chose this fqlearn to test unit the module steamtable and then improve
the plot, i follow this contributing?

Em qua., 17 de jan. de 2024 às 22:05, Ivan Ogasawara <
***@***.***> escreveu:

**Comment by RafaelNobre21** [comment]
or you want me to contact the evervino first?

Em qui., 18 de jan. de 2024 às 11:09, Rafael Pereira ***@***.***>
escreveu:

**Comment by xmnlab** [comment]
yes, please, contact him first. thanks
