### ISSUE TITLE
New Intern: Ana Paula Morais Krelling

### ISSUE THREAD

**Issue by apkrelling** [OpenScienceLabs/request-forms#55]
### Send your Project Proposal to Open Science Lab email

- [X] I have sent my Project Proposal to opensciencelabs@gmail.com

### Code of Conduct

- [X] I have read the [Code of Conduct](https://opensciencelabs.org/guidelines/coc/) and I agree.

**Comment by EverVino** [comment]
@xmnlab ArxLang related

**Comment by xmnlab** [comment]
Thanks @apkrelling ! Thank you for applying to the internship project program.
We're pleased to inform you that your application is complete and in excellent condition.

We will announce the final result on February 14, 2024.

In the mean, if you want to keep contributing to the project for other issues as well, let me know and I can pointing you to other issues, and I will keep mentoring.

**Comment by apkrelling** [comment]
Sounds great, thank you!

**Comment by xmnlab** [comment]
thanks @apkrelling ! glad to see you onboard!
