### ISSUE TITLE
New Intern: Mohd Quamar Tyagi

### ISSUE THREAD

**Issue by Tyagiquamar** [OpenScienceLabs/request-forms#57]
### Send your Project Proposal to Open Science Lab email

- [X] I have sent my Project Proposal to opensciencelabs@gmail.com

### Code of Conduct

- [X] I have read the [Code of Conduct](https://opensciencelabs.org/guidelines/coc/) and I agree.

**Comment by xmnlab** [comment]
I am closing this issue as the application process for the cycle 2024/01 is already closed.
thanks for your participation
