### ISSUE TITLE
New Intern: Korada Vishal

### ISSUE THREAD

**Issue by Vishalk91-4** [OpenScienceLabs/request-forms#58]
### Send your Project Proposal to Open Science Lab email

- [X] I have sent my Project Proposal to opensciencelabs@gmail.com

### Code of Conduct

- [X] I have read the [Code of Conduct](https://opensciencelabs.org/guidelines/coc/) and I agree.

**Comment by xmnlab** [comment]
Thank you @Vishalk91-4 ! glad to see you around!
