### ISSUE TITLE
New Intern: Faith Hunja

### ISSUE THREAD

**Issue by faithhunja** [OpenScienceLabs/request-forms#59]
### Send your Project Proposal to Open Science Lab email

- [X] I have sent my Project Proposal to opensciencelabs@gmail.com

### Code of Conduct

- [X] I have read the [Code of Conduct](https://opensciencelabs.org/guidelines/coc/) and I agree.

**Comment by xmnlab** [comment]
thanks @faithhunja .. glad to have you onboard!
