### ISSUE TITLE
New Mentor: Fausto Mauricio Lagos Suarez

### ISSUE THREAD

**Issue by piratax007** [OpenScienceLabs/request-forms#6]
# ¡Convocatoria para Mentores!

Open Science Labs (OSL) es una comunidad que ofrece un espacio abierto para compartir, aprender y enseñar temas relacionados a Ciencia Abierta y Tecnologías computacionales (Python, C++, JavaScript, Machine learning, DevOps, etc) al público de Latinoamérica, pero no restringido a ello. Nuestra comunidad no intenta crear la rueda, sino que queremos integrar con otras comunidades y unir esfuerzos. 

Si quieres ser mentore/a en nuestra comunidad, llene el siguiente formulario:

```{note}
(*) Obligatorio.
```

- **E-mail`*`**: piratax007@gmail.com
- **Nombre completo`*`**: Fausto Mauricio Lagos Suarez
- **Áreas de interés para las mentorías`*`**: Python, Golang, Privacidad
- **URL del perfil en Linkedin**: https://www.linkedin.com/in/fausto-mauricio-lagos-suarez-5924a5219
- **URL del perfil en Twitter**: https://twitter.com/piratax007
- **URL del perfil en GitHub**: https://github.com/piratax007

He leído el [Código de Conducta](https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo`*`: 
- [X] Sí

He leído la [Guía de Mentorías](https://opensciencelabs.github.io/mentoring/guide-en.html)`*`: 
- [X] Sí

**Comment by xmnlab** [comment]
@piratax007 nos podrías enviar un imagen tuya de perfil o un link de una imagen tuya de perfil?
vamos a crear una página para mentores y te vamos a incluir allá.
también vamos a necesitar una bio tuya para agregar a esta página. 

aquí está una versión inicial para autores de blog posts como ejemplo: https://opensciencelabs.github.io/articles/authors/alan-hurtarte.html

**Comment by piratax007** [comment]
**Datos bibliográficos**

Fausto Mauricio Lagos Suarez, 
Matemático con matetría en ingeniería computacional y matemática. 
Área de investigación: Ecuaciones Diferenciales Ordinarias
Activista por el Software Libre y el Conocimiento Abierto 
Desarrollador de Software (Criptología) en el equipo del Centro de Autonomía Digital en Quito (Ecuador)

![photo1643938385](https://user-images.githubusercontent.com/23584921/152459066-567c40ee-6575-4386-8345-d8941446cb78.jpeg)

**Comment by xmnlab** [comment]
gracias @piratax007 pronto estaremos agregando tu página de mentor!

**Comment by EverVino** [comment]
Hola @piratax007 , no te vimos en nuestra última reunión, estamos coordinando una nueva, nos podrías indicar tu disponibilidad de tiempo aquí -> https://strawpoll.com/kjz68rgeo (esta pagina nos permite coordinar nuestros tiempos con diferentes zonas horarias).  Gracias.

**Comment by xmnlab** [comment]
@piratax007 , nos gustaría comentarte que estamos organizando nuevamente el programa de mentoría y nos gustaría saber si aún tienes interés de ser un mentor asociado a Open Science Labs.
gracias por la atención.

**Comment by piratax007** [comment]
Buena noche @xmnlab, discúlpame por responder pasado tanto tiempo, para responder a tu pregunta, estaré encantado en poder colaborar con las mentorías que estén a mi alcance atender.

Gracias, quedo atento.

**Comment by xmnlab** [comment]
Estoy trabajando en la página de mentoras/es, y ya voy agregarte allá, y creo que hasta la próxima semana ya va a estar online.

Vamos a tomar 2 semanas de descanso y después ya volvemos con más novedades :)

**Comment by xmnlab** [comment]
@piratax007 ya hemos subido la primera versión de la página de mentoras/es: https://opensciencelabs.org/mentoring/mentors/

esta semana ya te voy a agregar allá.
una consulta, cuántos cupos libres tendrías para las mentorías?

muchas gracias

**Comment by piratax007** [comment]
Saludos, por ahora considero que no más de dos o tres debido a que el 2023 lo inicio con programa de mentorías en la empresa.

Gracias.

**Comment by xmnlab** [comment]
hecho! https://opensciencelabs.org/mentoring/mentors/
otra consulta, vamos a incluir en la página los idiomas que cada mentor puede dar las mentorías.
me podrías informar en cuál idiomas podrías dar tus mentorías?

**Comment by piratax007** [comment]
Saludos, podría atender mentorías en inglés y español

**Comment by xmnlab** [comment]
super! muchas gracias. ya lo voy a actualizar. 
y ya voy a cerrar esta issue ya que tenemos todas las informaciones por el momento.
muchas gracias!!
