### ISSUE TITLE
Bhanupriya Gupta

### ISSUE THREAD

**Issue by bhanupgpt** [OpenScienceLabs/request-forms#60]
### Send your Project Proposal to Open Science Lab email

- [X] I have sent my Project Proposal to opensciencelabs@gmail.com

### Code of Conduct

- [X] I have read the [Code of Conduct](https://opensciencelabs.org/guidelines/coc/) and I agree.

**Comment by xmnlab** [comment]
hi @bhanupgpt, thanks for applying to the OSL Internship.

The call for interns for the cycle 2024-01 is already closed.

We will post information about the next cycle soon.

But you can already check the projects that participated in the cycle 2024-01 and get involved to that projects: https://opensciencelabs.org/blog/call-for-interns-2024-01/

So join us on discord: https://opensciencelabs.org and get involved to the projects, so you will be more prepared for next cycle.

See you!
