### ISSUE TITLE
Solicitud de mentoría: Sandro Loch

### ISSUE THREAD

**Issue by esloch** [OpenScienceLabs/request-forms#7]
# ¡Solicitud de mentorías!

Open Science Labs (OSL) es una comunidad que ofrece un espacio abierto para compartir, aprender y enseñar temas relacionados a Ciencia Abierta y Tecnologías computacionales (Python, C++, JavaScript, Machine learning, DevOps, etc) al público de Latinoamérica, pero no restringido a ello. Nuestra comunidad no intenta crear la rueda, sino que queremos integrar con otras comunidades y unir esfuerzos. 

Si quieres solicitar mentoría, llene el siguiente formulario:

```{note}
(*) Obligatorio.
```

- **E-mail`*`**: es.loch@gmail.com
- **Nombre completo`*`**: Sandro Loch
- **Áreas de interés para la mentoría`*`**: Python, Django
- **URL del perfil en Linkedin**: 
- **URL del perfil en Twitter**: 
- **URL del perfil en GitHub**: 

He leído el [Código de Conducta](https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo`*`: 
- [ X] Sí

He leído la [Guía de Mentorías](https://opensciencelabs.github.io/mentoring/guide-en.html)`*`: 
- [ X] Sí

Puntos a trabajar en la mentoría:
-  Uso de desarrollo dirigido por comportamiento BDD.
 - Pruebas automatizadas con PYTEST en CI/CD.
-  Montar test suite desde test cases DJANGO.

**Comment by petrizzo** [comment]
Saludos @esloch nos gustaría contar con un imagen tuya de perfil que no exceda los 250kb para poder ubicar en la página de mentores que vamos a crear, en la que estarías incluido. En esa página vamos a incluir una bio tuya.

Si necesitas ayuda, mira esta página que hemos creado para autores de blog post para nuestro proyecto, seguro te resulta interesante como ejemplo: https://opensciencelabs.github.io/articles/authors/alan-hurtarte.html

Gracias!

**Comment by xmnlab** [comment]
@petrizzo la solicitud de mentoría es distinta a la convocatoria de mentores.
@esloch está solicitando una mentoría, así que no necesitamos incluirlo en la página de mentores.

quizá el nombre es un poco confuso XD lo siento. si tienes un nombre mejor para evitar confusiones, cualquier idea es bienvenida :)

**Comment by xmnlab** [comment]
@esloch podrías darnos detalles de los puntos que quieres trabajar en la mentoría?
así podemos, así podemos contactar al/ a la mentor/a con más informaciones.

**Comment by petrizzo** [comment]
@xmnlab lo confuso no es el nombre. Es que los textos que acompañan a cada formulario es exactamente igual! 

En realidad no me percaté que el título venía del formulario y pensé que lo colocaba el aspirante a mentor.

Dicho esto, sugiero que no se utilice el mismo texto en ambos formularios y que, además, se cambie "solicitud" por "Requerimiento de mentoría" en el caso de que alguien pida a OSL que le ubique una persona para ser mentor.

En el caso de la de "¡Convocatoria de mentorías!" creo que lo apropiado es "¡Convocatoria a mentores/as!"

**Comment by xmnlab** [comment]
para mí tiene sentido. gracias, lo haré estos cambios en los próximos dias. 
Si quieres proponer cualquier otro cambio, estés a gusto de enviar un PR, los archivos están aquí: https://github.com/OpenScienceLabs/request-forms/tree/main/.github/ISSUE_TEMPLATE

**Comment by esloch** [comment]
> Saludos @esloch nos gustaría contar con un imagen tuya de perfil que no exceda los 250kb para poder ubicar en la página de mentores que vamos a crear, en la que estarías incluido. En esa página vamos a incluir una bio tuya.
> 
> Si necesitas ayuda, mira esta página que hemos creado para autores de blog post para nuestro proyecto, seguro te resulta interesante como ejemplo: https://opensciencelabs.github.io/articles/authors/alan-hurtarte.html
> 
> Gracias!

Quedo muy bueno!
Gracias Mariangela!!!

**Comment by xmnlab** [comment]
@esloch aún necesitas mentoría? me avisas si aún quieres seguir con esta solicitud! gracias!

**Comment by xmnlab** [comment]
como no hemos recibido respuestas, estoy finalizando esta issue.
@esloch esté a gusto de re-abrirla si aún estás interesado en este tema.
muchas gracias

**Comment by esloch** [comment]
Gracias @xmnlab!
