### ISSUE TITLE
NEW CONTRIBUTOR: Luis Gago Casas

### ISSUE THREAD

**Issue by luisgagocasas** [OpenScienceLabs/request-forms#8]
# ¡Convocatoria para Colaboración!

Open Science Labs (OSL) es una comunidad que ofrece un espacio abierto para compartir, aprender y enseñar temas relacionados a Ciencia Abierta y Tecnologías computacionales (Python, C++, JavaScript, Machine learning, DevOps, etc) al público de Latinoamérica, pero no restringido a ello. Nuestra comunidad no intenta crear la rueda, sino que queremos integrar con otras comunidades y unir esfuerzos. 

Si quieres colaborar a nuestra comunidad llene el formulario a seguir:

```{note}
(*) Obligatorio.
```

- **E-mail`*`**: luisgago@lagc-peru.com
- **Nombre completo`*`**: Luis Gago Casas
- **Área de interés`*`**:
  - [x] DevOps
  - [ ] Creación de Artículos (blog)
  - [ ] Producción de Videos (youtube)
  - [ ] Community Management
  - [ ] Social Media
  - [ ] Diversidad, Equidad e Inclusión
  - [x] Organización de Eventos
  - [ ] Documentación
  - [x] Mentoría
  - [x] Gestión de Proyectos
- **¿Por qué quiero colaborar a la comunidad OSL?`*`**: Me gusta colaborar en comunidades enseñar lo aprendido y aprender de la experiencia de los participantes.
- **Horas semanales disponibles para dedicarme a la comunidad OSL`*`**:
  - [x] 2 horas/semana
  - [ ] 4 horas/semana
  - [ ] 6+ horas/semana
- **URL del perfil en Linkedin**:  https://www.linkedin.com/in/luisgagocasas/
- **URL del perfil en Twitter**: https://twitter.com/LuisGagoCasas
- **URL del perfil en GitHub**: https://github.com/luisgagocasas
- **Bio (una descripción sobre ti, similar a la usada en Linkdin o en tu CV)`*`**: Apasionado por aprender cosas nuevas y amo la programación.

**He leído el Código de Conducta de OSL (https://opensciencelabs.github.io/coc/coc-es.html) y estoy de acuerdo`*`**:

- [x] Sí

**Comment by xmnlab** [comment]
Hola @luisgagocasas, tu colaboración será bastante apreciada por la comunidad de OSL :)

tenemos una reunión semanal para coordinar las actividades. Agrega nuestro calendario en tu google calendar: http://calendar.opensciencelabs.org/

nos vemos en la próxima semana!

ps: vamos a dejar esta issue abierta, así podemos usarla para discutir algunos puntos

**Comment by xmnlab** [comment]
PS: el canal principal de nuestra comunidad es http://discord.opensciencelabs.org

**Comment by EverVino** [comment]
Hola @luisgagocasas, no te vimos en nuestra última reunión, estamos coordinando una nueva, nos podrías indicar tu disponibilidad de tiempo aquí -> https://strawpoll.com/kjz68rgeo (esta pagina nos permite coordinar nuestros tiempos con diferentes zonas horarias) Gracias.

**Comment by luisgagocasas** [comment]
@EverVino , hola recien e agregado el calendario y acabo de añadir mi disponibilidad. nos vemos en la próxima reunion.

**Comment by EverVino** [comment]
Gracias Luis! nos vemos.

**Comment by xmnlab** [comment]
Bienvenido @luisgagocasas !
