### ISSUE TITLE
NEW CONTRIBUTOR: LeonGto

### ISSUE THREAD

**Issue by LeonGto** [OpenScienceLabs/request-forms#9]
# ¡Convocatoria para Colaboración!

Open Science Labs (OSL) es una comunidad que ofrece un espacio abierto para compartir, aprender y enseñar temas relacionados a Ciencia Abierta y Tecnologías computacionales (Python, C++, JavaScript, Machine learning, DevOps, etc) al público de Latinoamérica, pero no restringido a ello. Nuestra comunidad no intenta crear la rueda, sino que queremos integrar con otras comunidades y unir esfuerzos. 

Si quieres colaborar a nuestra comunidad llene el formulario a seguir:

```{note}
(*) Obligatorio.
```

- **E-mail`*`**:
- **Nombre completo`*`**:
- **Área de interés`*`**:
  - [ ] DevOps
  - [ ] Creación de Artículos (blog)
  - [ ] Producción de Videos (youtube)
  - [ ] Community Management
  - [ ] Social Media
  - [ ] Diversidad, Equidad e Inclusión
  - [ ] Organización de Eventos
  - [ ] Documentación
  - [ ] Mentoría
  - [ ] Gestión de Proyectos
- **¿Por qué quiero colaborar a la comunidad OSL?`*`**:
- **Horas semanales disponibles para dedicarme a la comunidad OSL`*`**:
  - [ ] 2 horas/semana
  - [ ] 4 horas/semana
  - [ ] 6+ horas/semana
- **URL del perfil en Linkedin**: 
- **URL del perfil en Twitter**: 
- **URL del perfil en GitHub**:
- **Bio (una descripción sobre ti, similar a la usada en Linkdin o en tu CV)`*`**: 

**He leído el Código de Conducta de OSL (https://opensciencelabs.github.io/mentoring-guideline/coc-es.html) y estoy de acuerdo`*`**:
- [ ] Sí

**Comment by xmnlab** [comment]
@LeonGto , podrías llenar el primer comentarios con tus datos? https://github.com/OpenScienceLabs/request-forms/issues/9#issue-1125016155

**Comment by xmnlab** [comment]
PS: el canal principal de nuestra comunidad es http://discord.opensciencelabs.org

**Comment by xmnlab** [comment]
hola @LeonGto , necesitamos que llenes tu primer comentario con los datos solicitados.
hoy tenemos reunión comunitaria, más informaciones en nuestro calendario: http://calendar.opensciencelabs.org/
nos vemos allá! saludos!

**Comment by xmnlab** [comment]
@LeonGto , nos gustaría saber si aún estás interesado en colaborar a Open Science Labs. sería un gusto tenerte aboardo. avisame si tienes alguna duda. saludos!

**Comment by xmnlab** [comment]
como no hemos recibido respuestas, estoy finalizando esta issue.
@LeonGto esté a gusto de reabrir esta issue si aún estás interesado en este tema.
muchas gracias
